# Use official Node.js image as a base
FROM node:14 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install @mui/material @emotion/react @emotion/styled

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Use nginx image as a base for serving static files
FROM nginx:alpine

# Copy build files from previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to run the application
CMD ["nginx", "-g", "daemon off;"]
